trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    displayName: 'Executando o Build'
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     displayName: 'Executando os testes'